backend:
  name: github
  repo: liberalreporters/babatundeogunlade-site
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "news"
    label: "News & Campaign Updates"
    folder: "content/news"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      
